added index markup
htmlacademy-adaptive/1277737-pink-21 pull request #2
Opened 2020-11-16 18:49 UTC by artamonster

added index markup

2020-11-17 09:05 UTC, Zakamsky requested changes
Добротно и тщательно сделана разметка по БЭМ, но есть три маленькие ошибки, две из которых больше похожи на опечатки.

2020-11-17 09:05 UTC, Zakamsky commented on source/index.html
> +  <div class="footer__social social">
Элемент блока без самого блока, но возможно это просто опечатка.

2020-11-19 17:30 UTC, artamonster commented
Пардон, случайно запихнул страничку с Формой в ветку module2-task1

2020-11-20 14:50 UTC, Zakamsky reviewed
Разметка добротная, нарушений нет, но написал один комментарий-рассуждение и там на каждой странице осталась не исправлена одна строка. Но думаю это скорее опечатка, т.ч. в зачет.
з.ы. если подумаешь о правка в форме, я бы еще обратил внимание на однородность, просто где то заголовок блока в легенде, а где то в параграфе, или на это есть свой резон?

2020-11-20 14:50 UTC, Zakamsky commented on source/index.html
> +  <section class="page-footer__contacts contacts">
page-footer__contacts а это тут что у нас такое?

2020-11-20 14:50 UTC, Zakamsky commented on source/contest.html
> +    <fieldset class="contest__user">
Вот тут строго говоря не ошибка с т.ч. зрения критериев академии, но я хочу обратить твое внимание на тонкий момент:

`<main class="page-main contest">`
один элемент сразу на два блока и дальше начинает разрастаться об блока внутрь друг друга...
Это немного портит картину абсолютно независимых блоков (хотя подобное даже в демках есть) это может вызвать проблемы с написанием стилей и разделением их на отдельные файлы, был случай когда студент был вынужден править штмл во время защиты проекта и переписывать  стили блоков...
но даже если мы уверены что такого не будет я бы предложил рассмотреть такой вариант:
класс `.contest` передать самой форме, т.е. сделать независимым блоком форму, а для внешних стилей можно ее миксануть с `page-main__contest` если нужно.

2020-11-20 14:50 UTC, Zakamsky commented on source/contest.html
> +  <div class="footer__social social">
опять у нас тут элемент без блока, но это видимо уже опечатка...

2020-11-20 14:51 UTC, merged